[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "Sobre"
    url = "/about"
    weight = 2

[[main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/fcidade/"
    weight = 3

[[main]]
    identifier = "categories"
    name = "Categorias"
    url = "/categories"
    weight = 4

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 5
    
# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/fcidade/"
    weight = 3