[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

# [[main]]
#     identifier = "posts"
#     name = "Posts"
#     url = "/posts"
#     weight = 2

[[main]]
    identifier = "about"
    name = "Sobre"
    url = "/about"
    weight = 3

[[main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/fcidade/"
    weight = 4

[[main]]
    identifier = "categories"
    name = "Categorias"
    url = "/categories"
    weight = 5

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 6
    
# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/fcidade/"
    weight = 3